### ISSUE TITLE
Dockerize All

### ISSUE THREAD

**Issue by GNZTMPZ** [wholesomeland/robot-international#2]
Hey there.

I need help for dockerizing the bot, both dockerfile and docker-compose.
So, for both frontend and bot dockerfile (e.g. i want to dockerize the bot sections) it works on separate private repos (like build, push to docker hub, and use it for productions).
However, i think i did something bad but idk what is it. maybe someone can help me?

For docker-compose, i don't know how to do it because i never use it or create it.
but since i heard docker-compose is good for running multiple containers at once, it will be nice to have it on our project.

Pull request are much appreciated.

Regards.
Matt.

**Comment by RishiKumarRay** [comment]
I can help in this , let me summarise the task
We have to create separate docker file for frontend and bot after that we have to write a docker compose integrating both to run this project.

**Comment by RishiKumarRay** [comment]
Assign me please , i might use multiple PR to work on this one by one

**Comment by GNZTMPZ** [comment]
> Assign me please , i might use multiple PR to work on this one by one

Done!

Thank you so much for the help, @RishiKumarRay 🙏

**Comment by RishiKumarRay** [comment]
It's late here now , i might work on this from tomorrow, and let you know all the progress thanks :)

**Comment by GNZTMPZ** [comment]
> It's late here now , i might work on this from tomorrow, and let you know all the progress thanks :)

Sure!

It's 2:43AM over here aswell 😬 
Anyway, Thank you so much for the help. 😊

**Comment by RishiKumarRay** [comment]
@GNZTMPZ i have added frontend dockerfile please check

**Comment by GNZTMPZ** [comment]
gimme a sec :)

**Comment by GNZTMPZ** [comment]
> @GNZTMPZ i have added frontend dockerfile please check

lgtm

i might reformat the codes with black soon, gimme a moment

**Comment by RishiKumarRay** [comment]
@RishiKumarRay the frontend docker file is working successfully, although i saw a docker file in the bot directory , i tried running that by fixing dockerfile , there are some errors in the code itself which you need to fix because i tried running bot locally the errors were same , so you need to have a look on that , maybe after that we can make a separte dockerfile for that too, if want. otherwise the frontend application is working fine and dockerfile too if you want i will add docker compose file for frontend only.

**Comment by RishiKumarRay** [comment]
the error while running bot was this 
![Screenshot from 2022-02-04 09-21-12](https://user-images.githubusercontent.com/87641376/152479640-5bdb79a2-7494-407c-a112-fc83dd99b50a.png)

**Comment by GNZTMPZ** [comment]
> the error while running bot was this ![Screenshot from 2022-02-04 09-21-12](https://user-images.githubusercontent.com/87641376/152479640-5bdb79a2-7494-407c-a112-fc83dd99b50a.png)

ah, i get it.. maybe because there's some secrets the bot needed to run smoothly.. 
it's [over here](https://github.com/wholesomeland/robot-international/blob/master/bot/example.env)
but i can assure you, i could run the bot perfectly on different repository
here's some proof: 
![image](https://user-images.githubusercontent.com/27568445/152479982-e25eb81b-0728-49d7-94cb-466040761d46.png)

you can ignore it anyway, up to you  :)

**Comment by RishiKumarRay** [comment]
@GNZTMPZ did you tested frontend dockerfile ?

**Comment by GNZTMPZ** [comment]
I did and it works :)

**Comment by RishiKumarRay** [comment]
@GNZTMPZ  great, then what's next ?

**Comment by GNZTMPZ** [comment]
all that's left is.. i think docker-compose

also, you might notice by the source code.. we're using mongodb as storing some data (e.g. user xp's and whatnot).
but i think adding mongodb to docker-compose is optional since we're using mongodb atlas for production use case XD

again, up to you :)

**Comment by RishiKumarRay** [comment]
can you give me some details like how you want the dockercompose ? or what things do you want in it? then i can work on this?

**Comment by GNZTMPZ** [comment]
uhh, we need to run the bot and frontend.
the docs is handled by github pages, so no need to worry about👍  *phew*

so we need 2 instances, i think, one is frontend and one is bot itself.
the frontend needs port 5000 so we can communicate with the frontend, while the bot doesnt need any port ig..

**Comment by RishiKumarRay** [comment]
ok , let me try that and i will get back to you , thanks 
meanwhile can you please merge the current pr i will open another for docker-compose

**Comment by GNZTMPZ** [comment]
> ok , let me try that and i will get back to you , thanks meanwhile can you please merge the current pr i will open another for docker-compose

Will do, thanks :D

**Comment by GNZTMPZ** [comment]
Tried my best to create the docker-compose, but it's always failed miserably :/
here's some screenshot: 
![image](https://user-images.githubusercontent.com/27568445/152628507-b3232abc-996e-45d2-b6e6-fc52e0265db8.png)

the docker-compose codes: 
```yaml
version: "3.9"

services:
  web:
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - 5000:5000
    environment:
      MONGODB_URI: the mongodb url
```

any ideas?

**Comment by RishiKumarRay** [comment]
You are trying on the windowss that's why this error is coming because on windows i guess we have to convert rpc , i had read about this when i helping out someone to make docker for windows.

**Comment by GNZTMPZ** [comment]
> You are trying on the windowss that's why this error is coming because on windows i guess we have to convert rpc , i had read about this when i helping out someone to make docker for windows.

Aww, too bad :(
I'll spin up a VM's and i'll let you know the progressions. Thanks.

**Comment by RishiKumarRay** [comment]
Yeah sure, i will also work on it today

**Comment by GNZTMPZ** [comment]
Hey man, I've tested the docker-compose and it works perfectly on my side. 
What do you think?

**Comment by RishiKumarRay** [comment]
Its great then, this docker compose will work on linux only , great you can now close this issue :) great work

**Comment by GNZTMPZ** [comment]
yayy! 🎉 

Again, Thank you for your help 🤗
